### ISSUE TITLE
Win10 ═ and winget epic fails

### ISSUE THREAD

**Issue by freeload101** [SillyTavern/SillyTavern-Launcher#38]
### Environment

Windows

### System

OS Name	Microsoft Windows 10 Pro Version	10.0.19045 Build 19045

### Describe the problem

* ═ chars break the script in windows 10
![image](https://github.com/SillyTavern/SillyTavern-Launcher/assets/4307863/2fec5333-f209-4906-82c4-908f51b0cc51)

* winget is so gross ... I feel like you could use powershell to download everything or if i had time to rewrite the entire thing in powershell I would .. you can install all the winget stuff with just powershell the windows I kill edge and the windows app store stuff on all my builds ... it looks like some places you use curl to 

 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern-Launcher/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)
